[features]
seeds = false
skip-lint = false
[programs.localnet]
note_taker = "Ev9dZC4VW8XJok85dEz3Er6psN2DdJkuSbYVzs8FGg8W"
notes = "9igkDBzMdRiteme5sxhLkVqWfYLDPLGt937GeWRZCK9T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dexter/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
